name: Develop Branch Integration

on:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 14 env
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Set Commit Message
        id: commit
        run: |
          [[ ${{ startsWith(github.head_ref, 'feature/') }} ]] && echo ::set-output name=message::"+semver: feature" \
          || echo ::set-output name=message::"+semver: patch"
      - name: Upgrading Version
        env:
          COMMIT_MSG: ${{ steps.commit.outputs.message }}
        run: |
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ secrets.GIT_USERNAME }}
          git add .
          git commit -m "$COMMIT_MSG" --allow-empty || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
        
        
        
        
        
        
